name: Build and Run
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
 
    runs-on: windows-latest

    env:
      Solution_Name: ReviewOfReviews.sln 
 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build with dotnet
      run: dotnet build --configuration Release
        
    - name: Run unit tests
      run: dotnet test --no-build --configuration Release

    - name: Run the Pipe Command
      run:  SenderModule\bin\Release\netcoreapp3.1\SenderModule.exe | ReceiverModule\bin\Release\netcoreapp3.1\ReceiverModule.exe

    - name: Generate coverage report
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Check Sender Coverage
      run: powershell ./SenderCoverage.ps1 -linerate 1

    - name: Check Receiver Coverage
      run: powershell ./ReceiverCoverage.ps1 -linerate 1

    - name: Install resharper
      run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
    
    - name: Run resharper inspection
      run: jb inspectcode ReviewOfReviews.sln /output=insreport.xml
       
    - name: Run resharper duplicate code check
      run: jb dupfinder ReviewOfReviews.sln  /output=dupreport.xml
       
    - name: Check Reports
      run: powershell ./resharper.ps1

    
    