name: Build and Run
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
 
    runs-on: windows-latest

    env:
      Solution_Name: ReviewOfReviews.sln
      Test_Project_Path: Sender.Tests\Sender.Tests.csproj
 
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Run unit tests
      run: dotnet test --no-build --configuration Release

 #    - name: Clear the test directory
 #      run: if exist  ("unittestproject\testresults\") (rmdir /s /q unittestproject\testresults\)
        
    - name: Generate coverage report
      run: dotnet test --collect:"XPlat Code Coverage"
      
    - name: Check Coverage
      run: powershell ./coverage.ps1 -linerate 1

    - name: Install resharper
      run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
        
    - name: Run resharper inspection
      run: jb inspectcode OddOrEven.sln /output=insreport.xml
       
    - name: Run resharper duplicate code check
      run: jb dupfinder OddOrEven.sln -o=dupreport.xml
       
    - name: Check Reports
      run: powershell ./resharper.ps1